name: test-coverage

on:
  push:
    branches: [main, master, Deterministic-QMC-algorithm]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::DT, any::htmltools
          needs: coverage

      - name: Compute coverage
        run: |
          coverage <- covr::package_coverage(type = "tests")
          print(coverage)
          cat("## Test coverage\n\n", file = Sys.getenv("GITHUB_STEP_SUMMARY"))
          cat(format(coverage), "\n", file = Sys.getenv("GITHUB_STEP_SUMMARY"), append = TRUE)
          covr::report(coverage, file = "coverage.html")
        shell: Rscript {0}

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
